name:                GadtParser
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/CarstenKoenig/GadtParser#readme
license:             BSD3
author:              Carsten Koenig
maintainer:          Carsten.Koenig@hotmail.de
copyright:           2019 Carsten Koenig
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - megaparsec

ghc-options:
  -Wall

library:
  source-dirs:        src/lib


executables:
  GadtParser:
    source-dirs:      src/exe
    main:             Main.hs
    dependencies:
      - GadtParser


tests:
  spec:
    main:             Spec.hs
    source-dirs:      test/specs
    dependencies:
      - hspec
      - GadtParser
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover == 2.*

  doctest:
    main:              DocTest.hs
    source-dirs:       test/doctests
    dependencies:
      - doctest
      - doctest-discover