name:                GadtParser
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/CarstenKoenig/GadtParser#readme
license:             BSD3
author:              Carsten Koenig
maintainer:          Carsten.Koenig@hotmail.de
copyright:           2019 Carsten Koenig
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - megaparsec

ghc-options:
  -Wall

executables:
  GadtParser:
    source-dirs:      src
    main:             Main.hs
